name: intellimath_replica
description: Flutter Replica of IntelliMath

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # L10n
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  get_it: ^7.1.4
  provider: ^5.0.0
  darq: ^1.1.1

flutter:
  generate: true
  uses-material-design: true
